import { StyleSheet } from 'react-native';
import { colors, elevation, fontFamily, radius, spacing, typography } from '@trisakay/ui';

export const styles = StyleSheet.create({
  screen: { flex: 1 },
  heroBand: { height: 156 },
  motif: { position: 'absolute', top: -60, right: -60 },
  driverChip: {
    position: 'absolute',
    left: spacing.lg,
    top: spacing.xl,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 7,
    backgroundColor: 'rgba(255,255,255,0.16)',
    borderRadius: radius.pill,
    paddingVertical: 5,
    paddingLeft: 9,
    paddingRight: 12,
  },
  driverChipText: {
    fontSize: 11,
    lineHeight: 15,
    fontFamily: fontFamily.bold,
    letterSpacing: 0.9,
    textTransform: 'uppercase',
    color: colors.white,
  },
  badgeWrap: { alignItems: 'center', marginTop: -48, marginBottom: spacing.lg },
  markBadge: {
    width: 96,
    height: 96,
    borderRadius: radius.lg,
    backgroundColor: colors.white,
    alignItems: 'center',
    justifyContent: 'center',
    ...elevation.card,
  },
  mark: { width: 56, height: 66 },
  keyboardView: { flex: 1 },
  scrollContent: { flexGrow: 1, paddingHorizontal: spacing.xl, paddingBottom: spacing.xxxl },
  title: { ...typography.display, color: colors.ink, textAlign: 'center' },
  subtitle: {
    ...typography.body,
    color: colors.inkSoft,
    textAlign: 'center',
    marginTop: spacing.xs,
    marginBottom: spacing.xxl,
  },
  fields: { gap: spacing.lg, marginBottom: spacing.md },
  forgotLink: { alignSelf: 'flex-end', paddingVertical: spacing.sm, marginBottom: spacing.md },
  forgotLinkText: { ...typography.caption, color: colors.accentBlue, fontFamily: fontFamily.bold },
  dividerRow: { flexDirection: 'row', alignItems: 'center', gap: spacing.md, marginVertical: spacing.xl },
  dividerLine: { flex: 1, height: 1, backgroundColor: colors.line },
  dividerText: { ...typography.label, color: colors.inkSoft },
  authError: { ...typography.caption, color: colors.danger, marginBottom: spacing.md },
  registerLink: { marginTop: spacing.lg },
});
