import { StyleSheet } from 'react-native';
import { colors, radius, spacing, typography } from '@trisakay/ui';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: colors.bg },
  topRow: { paddingHorizontal: spacing.lg, paddingTop: spacing.xxl - 4, paddingBottom: spacing.xs },
  backButton: {
    width: 40,
    height: 40,
    borderRadius: 13,
    backgroundColor: colors.panel,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: colors.accentBlue,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.09,
    shadowRadius: 8,
    elevation: 2,
  },
  scrollContent: { paddingHorizontal: spacing.lg, paddingBottom: spacing.xl, gap: spacing.lg },
  headerBlock: { gap: 2 },
  titleRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  title: { fontSize: 28, lineHeight: 34, fontFamily: typography.display.fontFamily, letterSpacing: -0.7, color: colors.ink },
  subtitle: { ...typography.caption, fontSize: 13, color: colors.inkSoft },
  listContent: { gap: spacing.md },
  cardRow: { padding: spacing.lg, gap: spacing.sm },
  subjectRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  subject: { ...typography.bodyStrong, color: colors.ink },
  formGap: { gap: spacing.md },
  newToggleText: { ...typography.body, color: colors.accentBlue },
  error: { ...typography.caption, color: colors.danger },
  fieldLabel: { ...typography.label, fontSize: 11, color: colors.inkSoft },
  pickerField: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm + 2,
    borderWidth: 1,
    borderColor: colors.line,
    borderRadius: radius.card,
    backgroundColor: colors.panel,
    paddingHorizontal: spacing.md + 2,
    minHeight: 52,
  },
  pickerIconTile: {
    width: 30,
    height: 30,
    borderRadius: radius.xs,
    backgroundColor: colors.accentBlueSoft,
    alignItems: 'center',
    justifyContent: 'center',
  },
  pickerFieldText: { ...typography.bodySm, fontSize: 14, color: colors.ink, flex: 1 },
  pickerFieldPlaceholder: { color: colors.inkFaint },
  pickerEmpty: {
    ...typography.body,
    color: colors.inkSoft,
    paddingVertical: spacing.md,
    paddingHorizontal: spacing.lg,
    textAlign: 'center',
  },
  pickerList: {
    borderWidth: 1,
    borderColor: colors.line,
    borderRadius: radius.sm,
    overflow: 'hidden',
  },
  evidenceRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.sm,
  },
  evidenceThumbWrap: {
    width: 72,
    height: 72,
  },
  evidenceThumb: {
    width: 72,
    height: 72,
    borderRadius: radius.card,
  },
  evidenceRemove: {
    position: 'absolute',
    top: -6,
    right: -6,
    backgroundColor: colors.ink,
    borderRadius: 999,
    width: 22,
    height: 22,
    alignItems: 'center',
    justifyContent: 'center',
  },
  evidenceAddTile: {
    width: 72,
    height: 72,
    borderRadius: radius.card,
    borderWidth: 1,
    borderColor: colors.line,
    borderStyle: 'dashed',
    backgroundColor: colors.panel,
    alignItems: 'center',
    justifyContent: 'center',
  },
  evidenceHint: {
    ...typography.caption,
    color: colors.inkFaint,
  },
  submittedWarning: {
    ...typography.caption,
    color: colors.danger,
  },
});
