import { StyleSheet } from 'react-native';
import { colors, fontFamily, radius } from '@trisakay/ui';

const softShadow = {
  shadowColor: colors.accentBlue,
  shadowOffset: { width: 0, height: 2 },
  shadowOpacity: 0.07,
  shadowRadius: 8,
  elevation: 2,
} as const;

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: colors.bg },
  flex: { flex: 1 },
  scrollContent: { paddingTop: 16, paddingHorizontal: 16, paddingBottom: 24, gap: 16 },
  error: { fontFamily: fontFamily.regular, fontSize: 13, lineHeight: 18, color: colors.danger },
  warning: { fontFamily: fontFamily.regular, fontSize: 13, lineHeight: 18, color: colors.inkSoft },

  // --- Home band ---
  bandBody: { gap: 12 },
  bandSub: { fontFamily: fontFamily.regular, fontSize: 13, lineHeight: 19, color: 'rgba(255, 255, 255, 0.72)' },
  statsRow: { flexDirection: 'row', paddingTop: 12, borderTopWidth: 1, borderTopColor: 'rgba(255, 255, 255, 0.14)' },
  statCol: { flex: 1, paddingHorizontal: 4 },
  statDivider: { borderLeftWidth: 1, borderLeftColor: 'rgba(255, 255, 255, 0.14)', paddingLeft: 16 },
  statNumber: { fontFamily: fontFamily.extrabold, fontSize: 22, lineHeight: 26, color: colors.white },
  statCaption: { fontFamily: fontFamily.regular, fontSize: 12, lineHeight: 16, color: 'rgba(255, 255, 255, 0.72)' },

  // --- Home body ---
  primaryShadow: {
    borderRadius: radius.lg2,
    shadowColor: colors.accentBlue,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 14,
    elevation: 4,
  },
  primaryCard: { flexDirection: 'row', alignItems: 'center', gap: 14, backgroundColor: colors.white, borderRadius: radius.lg2, padding: 16, minHeight: 44 },
  primaryTile: { width: 48, height: 48, borderRadius: 15, backgroundColor: colors.accentBlue, alignItems: 'center', justifyContent: 'center' },
  primaryBody: { flex: 1 },
  primaryTitle: { fontFamily: fontFamily.bold, fontSize: 16, lineHeight: 22, color: colors.ink },
  primarySub: { fontFamily: fontFamily.regular, fontSize: 12.5, lineHeight: 18, color: colors.inkSoft },
  sectionLabel: {
    fontFamily: fontFamily.bold,
    fontSize: 11,
    lineHeight: 15,
    letterSpacing: 0.7,
    textTransform: 'uppercase',
    color: colors.inkSoft,
    marginBottom: 8,
  },
  issueGrid: { flexDirection: 'row', gap: 8 },
  issueCard: {
    flex: 1,
    alignItems: 'center',
    gap: 8,
    minHeight: 44,
    backgroundColor: colors.white,
    borderRadius: radius.card,
    paddingVertical: 12,
    paddingHorizontal: 10,
    ...softShadow,
  },
  issueLabel: { fontFamily: fontFamily.semibold, fontSize: 12.5, lineHeight: 16, color: colors.ink, textAlign: 'center' },
  caseList: { gap: 10 },
  caseCard: { backgroundColor: colors.white, borderRadius: radius.md3, paddingVertical: 14, paddingHorizontal: 16, gap: 10, ...softShadow },
  caseTop: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 8 },
  caseMeta: {
    flex: 1,
    fontFamily: fontFamily.semibold,
    fontSize: 11,
    lineHeight: 16,
    letterSpacing: 0.5,
    textTransform: 'uppercase',
    color: colors.inkFaint,
  },
  caseSubject: { fontFamily: fontFamily.semibold, fontSize: 15, lineHeight: 21, color: colors.ink },
  caseFooter: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  caseFooterText: { flex: 1, fontFamily: fontFamily.regular, fontSize: 12, lineHeight: 17, color: colors.inkSoft },

  // --- Filing: plain header + progress ---
  filingHeader: { flexDirection: 'row', alignItems: 'center', gap: 12, paddingHorizontal: 16, paddingBottom: 12 },
  headerTile: {
    width: 40,
    height: 40,
    borderRadius: 13,
    backgroundColor: colors.white,
    alignItems: 'center',
    justifyContent: 'center',
    ...softShadow,
  },
  filingTitle: { flex: 1, fontFamily: fontFamily.bold, fontSize: 18, lineHeight: 24, letterSpacing: -0.3, color: colors.ink },
  filingStep: { fontFamily: fontFamily.semibold, fontSize: 13, lineHeight: 18, color: colors.inkSoft },
  progressWrap: { paddingHorizontal: 16, paddingBottom: 12 },
  question: { fontFamily: fontFamily.bold, fontSize: 17, lineHeight: 23, letterSpacing: -0.2, color: colors.ink, marginBottom: 10 },
  block: { gap: 0 },

  // --- Filing: trip card ---
  tripCard: {
    backgroundColor: colors.white,
    borderRadius: radius.card,
    borderWidth: 1.5,
    borderColor: colors.accentBlue,
    padding: 14,
    gap: 12,
    shadowColor: colors.accentBlue,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 14,
    elevation: 3,
  },
  tripTop: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  tripTopBody: { flex: 1 },
  tripName: { fontFamily: fontFamily.semibold, fontSize: 14, lineHeight: 20, color: colors.ink },
  tripSub: { fontFamily: fontFamily.regular, fontSize: 12, lineHeight: 17, color: colors.inkSoft },
  linkButton: { minHeight: 44, justifyContent: 'center', paddingHorizontal: 4 },
  linkText: { fontFamily: fontFamily.semibold, fontSize: 13, lineHeight: 18, color: colors.accentBlue },
  tripBottom: { flexDirection: 'row', alignItems: 'flex-end', gap: 12, paddingTop: 12, borderTopWidth: 1, borderTopColor: colors.lineSoft },
  tripRail: { flex: 1 },
  tripFare: { fontFamily: fontFamily.bold, fontSize: 15, lineHeight: 20, color: colors.ink },
  altRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    minHeight: 44,
    marginTop: 10,
    backgroundColor: colors.white,
    borderRadius: radius.card,
    borderWidth: 1,
    borderColor: colors.line,
    padding: 13,
  },
  altRowActive: { borderWidth: 1.5, borderColor: colors.accentBlue },
  radio: { width: 18, height: 18, borderRadius: 9, borderWidth: 2, borderColor: colors.line, alignItems: 'center', justifyContent: 'center' },
  radioActive: { borderColor: colors.accentBlue },
  radioDot: { width: 8, height: 8, borderRadius: 4, backgroundColor: colors.accentBlue },
  altBody: { flex: 1 },
  pickerList: { marginTop: 10, backgroundColor: colors.white, borderRadius: radius.card, ...softShadow },
  pickerRow: { flexDirection: 'row', alignItems: 'center', gap: 10, minHeight: 48, paddingVertical: 8, paddingHorizontal: 14 },
  pickerRowDivider: { borderTopWidth: 1, borderTopColor: colors.lineSoft },
  categoryRow: { flexDirection: 'row', gap: 8 },
  categoryGrid: { gap: 8 },

  // --- Filing: step 2 ---
  summaryChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    minHeight: 44,
    backgroundColor: colors.fill,
    borderRadius: radius.sm2,
    paddingVertical: 10,
    paddingHorizontal: 12,
  },
  summaryText: { flex: 1, fontFamily: fontFamily.semibold, fontSize: 13, lineHeight: 18, color: colors.ink },
  fieldLabel: {
    fontFamily: fontFamily.bold,
    fontSize: 11,
    lineHeight: 15,
    letterSpacing: 0.7,
    textTransform: 'uppercase',
    color: colors.inkSoft,
    marginBottom: 8,
  },
  suggestions: { flexDirection: 'row', flexWrap: 'wrap', gap: 6, marginTop: 8 },
  suggestion: {
    minHeight: 36,
    justifyContent: 'center',
    borderRadius: radius.pill,
    borderWidth: 1,
    borderColor: colors.line,
    backgroundColor: colors.white,
    paddingHorizontal: 12,
  },
  suggestionActive: { backgroundColor: colors.accentBlue, borderColor: colors.accentBlue },
  suggestionText: { fontFamily: fontFamily.semibold, fontSize: 12, lineHeight: 16, color: colors.inkSoft },
  suggestionTextActive: { color: colors.white },
  hint: { fontFamily: fontFamily.regular, fontSize: 12, lineHeight: 17, color: colors.inkFaint, marginTop: 6 },
  photosHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 8 },
  counterPill: { borderRadius: radius.pill, backgroundColor: colors.fill, paddingVertical: 2, paddingHorizontal: 9 },
  counterText: { fontFamily: fontFamily.semibold, fontSize: 11, lineHeight: 16, color: colors.inkSoft },
  photoRow: { flexDirection: 'row', gap: 8, flexWrap: 'wrap' },
  photoSlot: {
    minHeight: 76,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    borderRadius: radius.sm2,
    borderWidth: 1,
    borderStyle: 'dashed',
    borderColor: 'rgba(0, 46, 96, 0.4)',
    paddingHorizontal: 14,
    backgroundColor: colors.white,
  },
  photoSlotText: { flex: 1, fontFamily: fontFamily.regular, fontSize: 12.5, lineHeight: 18, color: colors.inkSoft },
  photoSlotStrong: { fontFamily: fontFamily.semibold, color: colors.accentBlue },
  thumbWrap: { width: 76, height: 76 },
  thumb: { width: 76, height: 76, borderRadius: radius.sm2 },
  thumbRemove: {
    position: 'absolute',
    top: -6,
    right: -6,
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: colors.ink,
    alignItems: 'center',
    justifyContent: 'center',
  },
  bottomBar: {
    gap: 8,
    paddingTop: 12,
    paddingHorizontal: 16,
    backgroundColor: colors.white,
    borderTopWidth: 1,
    borderTopColor: colors.lineSoft,
  },
  errorBlock: { backgroundColor: colors.dangerSoft, borderRadius: radius.sm2, padding: 12 },
  errorBlockText: { fontFamily: fontFamily.regular, fontSize: 12.5, lineHeight: 18, color: colors.dangerPressed },

  // --- Case page ---
  caseBand: { gap: 8 },
  caseEyebrow: {
    fontFamily: fontFamily.bold,
    fontSize: 11,
    lineHeight: 16,
    letterSpacing: 0.7,
    textTransform: 'uppercase',
    color: 'rgba(255, 255, 255, 0.72)',
  },
  caseTitle: { fontFamily: fontFamily.extrabold, fontSize: 24, lineHeight: 30, color: colors.white },
  caseStatusRow: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  caseFiledText: { fontFamily: fontFamily.regular, fontSize: 12, lineHeight: 17, color: 'rgba(255, 255, 255, 0.72)' },
  nowCard: {
    flexDirection: 'row',
    gap: 12,
    backgroundColor: colors.white,
    borderRadius: radius.lg,
    borderWidth: 1.5,
    borderColor: colors.accentBlue,
    padding: 16,
  },
  nowBody: { flex: 1, gap: 2 },
  nowEyebrow: { fontFamily: fontFamily.bold, fontSize: 11, lineHeight: 15, letterSpacing: 0.7, textTransform: 'uppercase', color: colors.accentBlue },
  nowTitle: { fontFamily: fontFamily.bold, fontSize: 15, lineHeight: 21, color: colors.ink },
  nowText: { fontFamily: fontFamily.regular, fontSize: 12.5, lineHeight: 18, color: colors.inkSoft },
  reportCard: { backgroundColor: colors.white, borderRadius: radius.md3, padding: 16, gap: 10, ...softShadow },
  reportText: { fontFamily: fontFamily.regular, fontSize: 13.5, lineHeight: 20, color: colors.ink },
  linkedRow: { flexDirection: 'row', alignItems: 'center', gap: 10, minHeight: 44, backgroundColor: colors.white, borderRadius: radius.md3, padding: 14, ...softShadow },
  linkedBody: { flex: 1 },
  linkedTitle: { fontFamily: fontFamily.semibold, fontSize: 13.5, lineHeight: 19, color: colors.ink },
  linkedSub: { fontFamily: fontFamily.regular, fontSize: 12, lineHeight: 17, color: colors.inkSoft },
});
