import { StyleSheet } from 'react-native';
import { colors, fontFamily, radius } from '@trisakay/ui';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: colors.bg },
  header: { paddingHorizontal: 16, paddingBottom: 4 },
  closeTile: {
    width: 40,
    height: 40,
    borderRadius: 13,
    backgroundColor: colors.white,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: colors.accentBlue,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.09,
    shadowRadius: 8,
    elevation: 2,
  },
  content: { paddingTop: 8, paddingHorizontal: 20, paddingBottom: 24, gap: 16 },
  intro: { gap: 10 },
  introTile: { width: 56, height: 56, borderRadius: 18, backgroundColor: colors.dangerSoft, alignItems: 'center', justifyContent: 'center' },
  title: { fontFamily: fontFamily.extrabold, fontSize: 26, lineHeight: 32, letterSpacing: -0.6, color: colors.ink },
  sub: { fontFamily: fontFamily.regular, fontSize: 14, lineHeight: 21, color: colors.inkSoft },
  facts: {
    backgroundColor: colors.white,
    borderRadius: radius.lg,
    paddingVertical: 6,
    paddingHorizontal: 16,
    shadowColor: colors.accentBlue,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.07,
    shadowRadius: 8,
    elevation: 2,
  },
  factRow: { flexDirection: 'row', alignItems: 'center', gap: 12, paddingVertical: 12 },
  factDivider: { borderTopWidth: 1, borderTopColor: colors.lineSoft },
  factBody: { flex: 1 },
  factTitle: { fontFamily: fontFamily.semibold, fontSize: 14, lineHeight: 20, color: colors.ink },
  factSub: { fontFamily: fontFamily.regular, fontSize: 12.5, lineHeight: 18, color: colors.inkSoft },
  checkRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    minHeight: 44,
    backgroundColor: colors.white,
    borderRadius: radius.card,
    borderWidth: 1,
    borderColor: colors.line,
    paddingVertical: 13,
    paddingHorizontal: 14,
  },
  checkRowChecked: { borderWidth: 1.5, borderColor: colors.accentBlue },
  box: { width: 22, height: 22, borderRadius: 7, borderWidth: 2, borderColor: colors.line, alignItems: 'center', justifyContent: 'center' },
  boxChecked: { borderColor: colors.accentBlue, backgroundColor: colors.accentBlue },
  checkText: { flex: 1, fontFamily: fontFamily.semibold, fontSize: 13.5, lineHeight: 19, color: colors.ink },
  bottom: { paddingHorizontal: 20, gap: 6 },
  errorBlock: { backgroundColor: colors.dangerSoft, borderRadius: radius.sm2, padding: 12 },
  errorText: { fontFamily: fontFamily.regular, fontSize: 12.5, lineHeight: 18, color: colors.dangerPressed },
  keepButton: { minHeight: 48, alignItems: 'center', justifyContent: 'center' },
  keepText: { fontFamily: fontFamily.semibold, fontSize: 15, lineHeight: 20, color: colors.accentBlue },
});
