import { StyleSheet } from 'react-native';
import { colors, fontFamily, radius } from '@trisakay/ui';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: colors.bg },

  // --- Band ---
  bandBody: { gap: 14 },
  summaryRow: { flexDirection: 'row', gap: 18, alignItems: 'center' },
  scoreCol: { gap: 2 },
  score: { fontFamily: fontFamily.extrabold, fontSize: 44, lineHeight: 48, letterSpacing: -1.4, color: colors.white },
  starsRow: { flexDirection: 'row', gap: 2 },
  count: { fontFamily: fontFamily.regular, fontSize: 11.5, lineHeight: 16, color: 'rgba(255, 255, 255, 0.72)' },
  distCol: { flex: 1, gap: 4 },
  distRow: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  distStar: { width: 8, fontFamily: fontFamily.semibold, fontSize: 11, lineHeight: 14, color: 'rgba(255, 255, 255, 0.8)' },
  distTrack: { flex: 1, height: 6, borderRadius: 3, backgroundColor: 'rgba(255, 255, 255, 0.16)', overflow: 'hidden' },
  distFill: { height: 6, borderRadius: 3 },
  distPct: {
    width: 30,
    textAlign: 'right',
    fontFamily: fontFamily.semibold,
    fontSize: 11,
    lineHeight: 14,
    color: 'rgba(255, 255, 255, 0.8)',
  },
  filterRow: { flexDirection: 'row', gap: 6, flexWrap: 'wrap' },
  chip: {
    minHeight: 44,
    justifyContent: 'center',
    paddingHorizontal: 13,
    borderRadius: radius.pill,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.3)',
  },
  chipActive: { backgroundColor: colors.white, borderColor: colors.white },
  chipLabel: { fontFamily: fontFamily.semibold, fontSize: 12.5, lineHeight: 16, color: colors.white },
  chipLabelActive: { fontFamily: fontFamily.bold, color: colors.accentBlue },

  // --- List ---
  listContent: { paddingTop: 14, paddingHorizontal: 16, paddingBottom: 24, gap: 12 },
  error: { marginHorizontal: 16, marginTop: 8, fontFamily: fontFamily.regular, fontSize: 13, lineHeight: 18, color: colors.danger },
  mentionBlock: { gap: 8, marginBottom: 2 },
  sectionLabel: {
    fontFamily: fontFamily.bold,
    fontSize: 11,
    lineHeight: 15,
    letterSpacing: 0.7,
    textTransform: 'uppercase',
    color: colors.inkSoft,
  },
  mentionWrap: { flexDirection: 'row', flexWrap: 'wrap', gap: 6 },
  mentionChip: { flexDirection: 'row', alignItems: 'center', gap: 6, borderRadius: radius.pill, paddingVertical: 5, paddingHorizontal: 11 },
  mentionLabel: { fontFamily: fontFamily.semibold, fontSize: 12, lineHeight: 16 },
  mentionCount: { fontFamily: fontFamily.extrabold, fontSize: 12, lineHeight: 16 },
  noMatches: { textAlign: 'center', fontFamily: fontFamily.regular, fontSize: 13, lineHeight: 18, color: colors.inkSoft, paddingVertical: 16 },

  // --- Cards ---
  card: {
    backgroundColor: colors.white,
    borderRadius: radius.md3,
    paddingVertical: 14,
    paddingHorizontal: 16,
    gap: 8,
    shadowColor: colors.accentBlue,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.07,
    shadowRadius: 8,
    elevation: 2,
  },
  cardHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  date: { fontFamily: fontFamily.regular, fontSize: 12, lineHeight: 17, color: colors.inkFaint },
  comment: { fontFamily: fontFamily.regular, fontSize: 13.5, lineHeight: 20, color: colors.ink },
  tagRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 6 },
  tag: { borderRadius: radius.pill, paddingVertical: 3, paddingHorizontal: 9 },
  tagText: { fontFamily: fontFamily.semibold, fontSize: 11, lineHeight: 15 },
  reportFooter: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    minHeight: 44,
    paddingTop: 8,
    borderTopWidth: 1,
    borderTopColor: colors.lineSoft,
  },
  reportText: { fontFamily: fontFamily.semibold, fontSize: 13, lineHeight: 18, color: colors.accentBlue },
});
