import { StyleSheet } from 'react-native';
import { colors, elevation, radius, spacing, typography } from '@trisakay/ui';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: colors.bg },
  mapFill: { ...StyleSheet.absoluteFillObject },
  statusBadgeWrap: { position: 'absolute', top: spacing.xxl, left: spacing.lg },
  statusPill: {
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'flex-start',
    gap: 7,
    backgroundColor: colors.panel,
    borderRadius: radius.pill,
    paddingVertical: 9,
    paddingHorizontal: spacing.tight14,
    ...elevation.chip,
  },
  statusDot: { width: 9, height: 9, borderRadius: 4.5, backgroundColor: colors.accentBlue },
  statusLabel: { fontSize: 13, lineHeight: 17, fontFamily: typography.h3.fontFamily, color: colors.ink },

  // --- floating SOS (top-right, replaces the old Navigate map button) ---
  sosWrap: { position: 'absolute', top: spacing.xxl - 2, right: spacing.lg, alignItems: 'center', gap: 5 },
  sosChip: { backgroundColor: colors.white, borderRadius: radius.pill, paddingHorizontal: spacing.sm, paddingVertical: 3, ...elevation.chip },
  sosChipText: { fontSize: 10.5, lineHeight: 13, fontFamily: typography.bodyStrong.fontFamily, color: colors.danger },

  content: { gap: spacing.md },
  passengerScroll: { flexShrink: 1 },
  // The whole sheet body scrolls (passenger cards, error, notes, End trip), so a short screen never clips the bottom.
  passengerScrollContent: { gap: spacing.lg, paddingBottom: spacing.md },

  // --- next-stop block ---
  nextStopRow: { flexDirection: 'row', alignItems: 'flex-start', gap: spacing.md },
  nextStopTile: { width: 44, height: 44, borderRadius: radius.sm2, alignItems: 'center', justifyContent: 'center' },
  nextStopTilePickup: { backgroundColor: colors.accentBlueSoft },
  nextStopTileDropoff: { backgroundColor: colors.accentGreenSoft },
  pickupRing: { width: 14, height: 14, borderRadius: 7, borderWidth: 3, borderColor: colors.accentBlue },
  dropoffSquare: { width: 13, height: 13, borderRadius: 3, backgroundColor: colors.accentGreen },
  nextStopTextCol: { flex: 1, minWidth: 0, gap: 3 },
  nextStopEyebrow: { fontSize: 11.5, lineHeight: 15, letterSpacing: 0.6, textTransform: 'uppercase', fontFamily: typography.label.fontFamily, color: colors.inkSoft },
  nextStopAddress: { fontSize: 18, lineHeight: 24, fontFamily: typography.h1b.fontFamily, letterSpacing: -0.3, color: colors.ink },
  nextStopMeta: { fontSize: 13, lineHeight: 18, fontFamily: typography.body.fontFamily, color: colors.inkSoft },
  navigateTile: {
    width: 48,
    height: 48,
    borderRadius: radius.sm2 + 1,
    backgroundColor: colors.accentBlue,
    alignItems: 'center',
    justifyContent: 'center',
    ...elevation.chip,
  },
  navigateCol: { alignItems: 'center', gap: 3 },
  navigateLabel: { fontSize: 11, lineHeight: 14, fontFamily: typography.bodyStrong.fontFamily, color: colors.accentBlue },

  // --- passenger strip (README §4.1) ---
  passengerStrip: { gap: 10, backgroundColor: colors.bg, borderRadius: radius.card, padding: 10, paddingLeft: 12 },
  passengerTopRow: { flexDirection: 'row', alignItems: 'center', gap: spacing.md },
  passengerInfo: { flex: 1, minWidth: 0, gap: 2 },
  // Wraps so a long name or a narrow phone drops the status chip under the name instead of clipping it behind the options button.
  passengerNameRow: { flexDirection: 'row', flexWrap: 'wrap', alignItems: 'center', columnGap: spacing.sm, rowGap: 2 },
  passengerName: { ...typography.bodySm, fontSize: 15, color: colors.ink, maxWidth: '100%', flexShrink: 1 },
  passengerSub: { fontSize: 12.5, lineHeight: 17, fontFamily: typography.body.fontFamily, color: colors.inkSoft },
  statusChip: { borderRadius: radius.pill, paddingHorizontal: spacing.sm, paddingVertical: 3, flexShrink: 0 },
  statusChipArrived: { backgroundColor: colors.accentBlueSoft },
  statusChipOngoing: { backgroundColor: colors.accentGreenSoft },
  statusChipText: { fontSize: 10, lineHeight: 13, letterSpacing: 0.4, fontFamily: typography.label.fontFamily, color: colors.ink },
  statusChipTextArrived: { color: colors.accentBluePressed },
  statusChipTextOngoing: { color: colors.accentGreenPressed },
  optionsButton: {
    width: 44,
    height: 44,
    borderRadius: radius.sm2 + 1,
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: colors.line,
    alignItems: 'center',
    justifyContent: 'center',
  },

  // --- contact row (Call + Message, README §4.1/§4.3) ---
  contactRow: { flexDirection: 'row', gap: spacing.sm },
  contactButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    minHeight: 44,
    // minWidth 0 + hidden: a flex:1 button otherwise grows to its content (long "Message <name>" + badge) and spills over its neighbour.
    minWidth: 0,
    overflow: 'hidden',
    paddingHorizontal: spacing.sm,
    borderRadius: radius.md,
    backgroundColor: colors.accentBlueSoft,
  },
  contactButtonFilled: {
    backgroundColor: colors.accentBlue,
    shadowColor: colors.accentBlue,
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.25,
    shadowRadius: 14,
    elevation: 4,
  },
  contactLabel: { ...typography.bodySm, fontSize: 14, color: colors.accentBlue, flexShrink: 1 },
  contactLabelFilled: { fontSize: 14.5, color: colors.white },
  contactCountPill: { minWidth: 22, height: 22, borderRadius: 11, backgroundColor: colors.white, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 6 },
  contactCountPillText: { ...typography.label, fontSize: 12, textTransform: 'none', letterSpacing: 0, color: colors.accentBlue },

  // --- "then" list chat tile (README §4.2) ---
  thenChatButton: { width: 44, height: 44, borderRadius: radius.sm2, backgroundColor: colors.accentBlueSoft, alignItems: 'center', justifyContent: 'center' },
  thenUnreadBadge: {
    position: 'absolute',
    top: -4,
    right: -4,
    minWidth: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: colors.accentBlue,
    borderWidth: 2,
    borderColor: colors.white,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 3,
  },
  thenUnreadBadgeText: { ...typography.label, fontSize: 10.5, textTransform: 'none', letterSpacing: 0, color: colors.white },

  // --- primary action + hint ---
  primaryHint: { fontSize: 12.5, lineHeight: 18, fontFamily: typography.body.fontFamily, color: colors.inkSoft, textAlign: 'center' },
  handoffNotice: { ...typography.caption, color: colors.inkSoft },

  // --- cash row ---
  cashRowPending: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.md,
    borderWidth: 1.5,
    borderStyle: 'dashed',
    borderColor: colors.lineStrong,
    borderRadius: radius.lg,
    padding: spacing.tight10,
    paddingLeft: spacing.tight14,
  },
  cashRowTextCol: { flex: 1, minWidth: 0 },
  cashRowTitle: { ...typography.bodySm, fontSize: 14, color: colors.ink },
  cashRowSub: { fontSize: 12, lineHeight: 15, fontFamily: typography.body.fontFamily, color: colors.inkSoft },
  cashReceivedButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    minHeight: 44,
    paddingHorizontal: spacing.lg,
    borderRadius: radius.md,
    backgroundColor: colors.accentGreen,
  },
  cashReceivedButtonText: { ...typography.bodySm, fontSize: 14, color: colors.white },
  cashRowDone: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    backgroundColor: colors.accentGreenSoft,
    borderRadius: radius.lg,
    padding: spacing.tight14,
  },
  cashRowDoneText: { ...typography.bodySm, fontSize: 14, color: colors.accentGreenPressed },

  // --- passenger card wrapper ---
  passengerCard: { gap: spacing.md, borderRadius: radius.lg, borderColor: colors.lineSoft, padding: spacing.lg },
  aboardRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  aboardLabel: { ...typography.label, color: colors.inkSoft },

  // --- "then" list (remaining stops) ---
  thenSection: { paddingTop: spacing.md, borderTopWidth: 1, borderTopColor: colors.lineSoft, gap: spacing.md },
  thenEyebrow: { ...typography.label, fontSize: 11, color: colors.inkSoft },
  thenRow: { flexDirection: 'row', alignItems: 'center', gap: spacing.sm },
  thenNumber: { width: 26, height: 26, borderRadius: 13, backgroundColor: colors.fill, alignItems: 'center', justifyContent: 'center' },
  thenNumberText: { fontSize: 12, lineHeight: 15, fontFamily: typography.h3.fontFamily, color: colors.ink },
  thenTextCol: { flex: 1, minWidth: 0 },
  thenTitle: { fontSize: 14.5, lineHeight: 19, fontFamily: typography.bodySm.fontFamily, color: colors.ink },
  thenMeta: { fontSize: 12.5, lineHeight: 17, fontFamily: typography.caption.fontFamily, color: colors.inkSoft },
  thenOptionsButton: { width: 36, height: 36, borderRadius: radius.sm, backgroundColor: colors.bg, alignItems: 'center', justifyContent: 'center' },

  // --- mid-trip compatible request banner ---
  requestBanner: {
    backgroundColor: colors.accentBlueSoft,
    borderRadius: radius.lg,
    padding: spacing.tight10,
    paddingLeft: spacing.tight14,
    gap: spacing.sm,
  },
  requestBannerEyebrow: { fontSize: 11, lineHeight: 14, letterSpacing: 0.5, textTransform: 'uppercase', fontFamily: typography.h3.fontFamily, color: colors.accentBluePressed },
  requestBannerFare: { fontSize: 14, lineHeight: 19, fontFamily: typography.bodySm.fontFamily, color: colors.ink },
  requestBannerRow: { flexDirection: 'row', alignItems: 'center', gap: spacing.sm },
  requestBannerDecline: { width: 44, height: 44, borderRadius: radius.sm2, backgroundColor: colors.white, alignItems: 'center', justifyContent: 'center' },
  requestBannerAccept: { flex: 1, minHeight: 44, borderRadius: radius.md, backgroundColor: colors.accentBlue, alignItems: 'center', justifyContent: 'center' },
  requestBannerAcceptText: { ...typography.bodySm, fontSize: 14, color: colors.white },

  error: { ...typography.caption, color: colors.danger },
  endTripRow: { flexDirection: 'row' },

  // --- all-dropped-off panel ---
  doneWrap: { alignItems: 'center', gap: spacing.sm, paddingVertical: spacing.sm },
  doneCircle: { width: 60, height: 60, borderRadius: 30, backgroundColor: colors.accentGreenSoft, alignItems: 'center', justifyContent: 'center' },
  doneTitle: { fontSize: 21, lineHeight: 27, fontFamily: typography.h1b.fontFamily, letterSpacing: -0.4, color: colors.ink, textAlign: 'center' },
  doneBody: { ...typography.caption, color: colors.inkSoft, textAlign: 'center' },
  doneInfoNote: { flexDirection: 'row', gap: spacing.sm, backgroundColor: colors.fill, borderRadius: radius.md, padding: spacing.tight10, marginTop: spacing.xs },
  doneInfoNoteText: { flex: 1, fontSize: 12.5, lineHeight: 18, fontFamily: typography.body.fontFamily, color: colors.inkSoft },

  // --- options bottom sheet ---
  optionsBackdrop: { flex: 1, backgroundColor: colors.overlay, justifyContent: 'flex-end' },
  optionsSheet: { backgroundColor: colors.panel, borderTopLeftRadius: 28, borderTopRightRadius: 28, paddingHorizontal: spacing.lg, paddingTop: spacing.sm, paddingBottom: spacing.xxl, gap: spacing.xs },
  optionsHandle: { width: 40, height: 4, borderRadius: 2, backgroundColor: colors.lineStrong, alignSelf: 'center', marginBottom: spacing.md },
  optionsHeader: { flexDirection: 'row', alignItems: 'center', gap: spacing.md, paddingBottom: spacing.md },
  optionsHeaderTextCol: { flex: 1, minWidth: 0 },
  optionsHeaderName: { fontSize: 17, lineHeight: 22, fontFamily: typography.h1b.fontFamily, color: colors.ink },
  optionsHeaderMeta: { ...typography.caption, color: colors.inkSoft },
  optionsRow: { flexDirection: 'row', alignItems: 'center', gap: spacing.md, minHeight: 64, borderTopWidth: 1, borderTopColor: colors.lineSoft },
  optionsRowFirst: { borderTopWidth: 0 },
  optionsRowDisabled: { opacity: 0.4 },
  optionsTile: { width: 42, height: 42, borderRadius: radius.sm2, alignItems: 'center', justifyContent: 'center' },
  optionsTileBlue: { backgroundColor: colors.accentBlueSoft },
  optionsTileFill: { backgroundColor: colors.fill },
  optionsTileDanger: { backgroundColor: colors.dangerSoft },
  optionsRowTextCol: { flex: 1, minWidth: 0, gap: 2 },
  optionsRowTitle: { fontSize: 15, lineHeight: 20, fontFamily: typography.bodySm.fontFamily, color: colors.ink },
  optionsRowTitleDanger: { color: colors.danger },
  optionsRowDesc: { fontSize: 12.5, lineHeight: 17, fontFamily: typography.body.fontFamily, color: colors.inkSoft },
  optionsCloseButton: { marginTop: spacing.md, minHeight: 52 },
});
