import { StyleSheet } from 'react-native';
import { colors, elevation, radius, spacing, typography } from '@trisakay/ui';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: colors.bg },
  mapFill: { ...StyleSheet.absoluteFillObject },
  statusBadgeWrap: { position: 'absolute', top: spacing.xxl, left: spacing.lg },
  statusPill: {
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'flex-start',
    gap: 7,
    backgroundColor: colors.panel,
    borderRadius: radius.pill,
    paddingVertical: 7,
    paddingHorizontal: spacing.md + 1,
    ...elevation.chip,
  },
  statusDot: { width: 8, height: 8, borderRadius: 4, backgroundColor: colors.accentBlue },
  statusLabel: { ...typography.label, fontSize: 11, color: colors.accentBluePressed },
  /** Visual only — a real destination isn't plumbed to the driver client yet, see Phase 5 report. */
  navigateButton: {
    position: 'absolute',
    right: spacing.lg,
    top: spacing.xxl - 4,
    width: 44,
    height: 44,
    borderRadius: radius.md3,
    backgroundColor: colors.panel,
    alignItems: 'center',
    justifyContent: 'center',
    ...elevation.chip,
  },
  /** Radius 26 has no matching token step (nearest are 24/28) — a one-off literal, same resolution as the gate screens' card radius. */
  content: { gap: spacing.lg, borderTopLeftRadius: 26, borderTopRightRadius: 26 },
  passengerScroll: { flexShrink: 1 },
  passengerScrollContent: { gap: spacing.lg, paddingBottom: spacing.xs },
  aboardRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  aboardLabel: { ...typography.label, color: colors.inkSoft },
  passengerCard: { gap: spacing.md, borderRadius: radius.lg, borderColor: colors.lineSoft },
  passengerRow: { flexDirection: 'row', alignItems: 'center', gap: spacing.md },
  passengerInfo: { flex: 1, minWidth: 0 },
  passengerName: { ...typography.bodyStrong, color: colors.ink },
  seatsLabel: { ...typography.caption, color: colors.inkSoft },
  ongoingChip: { backgroundColor: colors.accentGreenSoft, borderRadius: radius.pill, paddingVertical: 4, paddingHorizontal: spacing.sm + 1 },
  ongoingChipText: { ...typography.label, fontSize: 10, color: colors.accentGreenPressed },
  cashRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: colors.fill,
    borderRadius: radius.card,
    paddingVertical: spacing.sm + 3,
    paddingHorizontal: spacing.md + 1,
  },
  cashLabel: { ...typography.bodyStrong, fontSize: 13.5, color: colors.ink },
  actions: { flexDirection: 'row', gap: spacing.md },
  actionButton: { flex: 1 },
  error: { ...typography.caption, color: colors.danger },
  sosBlock: { gap: spacing.xs, alignItems: 'center' },
  sosCaption: { ...typography.caption, color: colors.inkSoft },
  sectionLabel: { ...typography.label, color: colors.inkSoft, marginTop: spacing.sm },
});
