import { StyleSheet } from 'react-native';
import { colors, radius, spacing, typography } from '../../theme';

export const styles = StyleSheet.create({
  container: {
    backgroundColor: colors.white,
    borderBottomWidth: 1,
    borderBottomColor: colors.lineSoft,
    paddingHorizontal: spacing.md,
    paddingBottom: spacing.sm,
    gap: spacing.sm,
  },
  row: { flexDirection: 'row', alignItems: 'center', gap: spacing.sm },
  backButton: { width: 44, height: 44, alignItems: 'center', justifyContent: 'center' },
  textColumn: { flex: 1, gap: 2 },
  name: { ...typography.bodyStrong, fontSize: 16, lineHeight: 21, color: colors.ink },
  statusRow: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  dot: { width: 7, height: 7, borderRadius: 3.5 },
  dotRing: { width: 8, height: 8, borderRadius: 4, borderWidth: 2, borderColor: colors.accentGreen },
  dotSquare: { width: 8, height: 8, borderRadius: 2, backgroundColor: colors.accentBlue },
  statusText: { ...typography.body, fontSize: 12.5, lineHeight: 17, color: colors.inkSoft, flexShrink: 1 },
  plateTag: {
    backgroundColor: colors.white,
    borderWidth: 1.5,
    borderColor: colors.ink,
    borderRadius: radius.xs,
    paddingHorizontal: spacing.sm,
    paddingVertical: 2,
    alignItems: 'center',
  },
  plateLabel: { ...typography.label, fontSize: 8.5, letterSpacing: 0.8, color: colors.inkSoft },
  plateValue: { ...typography.h3, fontSize: 13, letterSpacing: 0.5, color: colors.ink },
  switcherScroll: { marginLeft: spacing.tight44 },
  switcher: { flexDirection: 'row', gap: 4, backgroundColor: colors.bg, borderRadius: radius.md, padding: 3 },
  switcherSegment: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    minHeight: 36,
    borderRadius: 9,
    paddingHorizontal: spacing.md,
    justifyContent: 'center',
  },
  switcherSegmentActive: {
    backgroundColor: colors.white,
    shadowColor: colors.accentBlue,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.12,
    shadowRadius: 4,
    elevation: 1,
  },
  switcherLabel: { ...typography.bodyStrong, fontSize: 13, color: colors.inkSoft },
  switcherLabelActive: { color: colors.accentBlue },
  switcherBadge: { minWidth: 18, height: 18, borderRadius: 9, backgroundColor: colors.accentBlue, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 4 },
  switcherBadgeText: { ...typography.label, fontSize: 10.5, textTransform: 'none', letterSpacing: 0, color: colors.white },
});
