import { StyleSheet } from 'react-native';
import { colors, radius, spacing, typography } from '@trisakay/ui';

/** Recipe 2 (phase0-notes.md) — bespoke panel shadow matching the README's exact weight, not `elevation.card`. */
const panelShadow = {
  shadowColor: colors.accentBlue,
  shadowOffset: { width: 0, height: 2 },
  shadowOpacity: 0.07,
  shadowRadius: 8,
  elevation: 2,
};

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: colors.bg },
  scrollContent: { paddingBottom: spacing.xl, gap: spacing.lg },
  /** Shadow never sits on the clipped GradientSurface itself — see phase0-notes.md Recipe 1. */
  heroShadow: {
    shadowColor: colors.accentBlue,
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.22,
    shadowRadius: 30,
    elevation: 10,
  },
  heroBand: {
    borderBottomLeftRadius: radius.heroBottom,
    borderBottomRightRadius: radius.heroBottom,
    paddingBottom: spacing.xxxl + spacing.lg,
  },
  motif: {
    position: 'absolute',
    top: -46,
    right: -52,
  },
  heroTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: spacing.lg,
    paddingTop: spacing.xxl,
  },
  heroEyebrow: { ...typography.label, fontSize: 11, color: colors.white, opacity: 0.66 },
  heroTitle: { fontSize: 26, lineHeight: 32, fontFamily: typography.display.fontFamily, letterSpacing: -0.6, color: colors.white, marginTop: 2 },
  editButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 7,
    backgroundColor: 'rgba(255,255,255,0.16)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.3)',
    borderRadius: radius.pill,
    paddingVertical: 8,
    paddingHorizontal: spacing.md + 2,
  },
  editButtonText: { ...typography.bodySm, fontSize: 13, color: colors.white },
  content: { paddingHorizontal: spacing.lg, gap: spacing.md },
  /** Pulled up over the hero/body seam so the avatar reads as floating. */
  identity: { alignItems: 'center', gap: spacing.xs, marginTop: -(spacing.xxxl + 6) },
  /** Non-clipping wrapper — the edit badge sits just outside the ring's own bounds. */
  avatarWrap: { position: 'relative' },
  avatarRing: {
    padding: 4,
    borderRadius: 999,
    backgroundColor: colors.bg,
  },
  avatarRingBorder: {
    padding: 2,
    borderRadius: 999,
    borderWidth: 1.5,
    borderColor: colors.accentGreenSoft,
  },
  avatarEditBadge: {
    position: 'absolute',
    bottom: -2,
    right: -2,
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: colors.accentGreen,
    borderWidth: 2.5,
    borderColor: colors.bg,
    alignItems: 'center',
    justifyContent: 'center',
  },
  editFieldWrap: { width: '100%', marginTop: spacing.sm },
  nameRow: { flexDirection: 'row', alignItems: 'center', gap: spacing.xs, marginTop: spacing.sm },
  name: { ...typography.h2, fontSize: 22, color: colors.ink },
  statusRow: { flexDirection: 'row', alignItems: 'center', gap: 6, marginTop: 2 },
  statusText: { ...typography.caption, color: colors.inkSoft },
  detailsCard: {
    backgroundColor: colors.panel,
    borderRadius: radius.md3,
    paddingHorizontal: spacing.lg,
    ...panelShadow,
  },
  detailRow: { flexDirection: 'row', alignItems: 'center', gap: spacing.md, paddingVertical: spacing.md - 1, borderBottomWidth: 1, borderBottomColor: colors.lineSoft },
  detailRowLast: { borderBottomWidth: 0 },
  detailIconTile: {
    width: 34,
    height: 34,
    borderRadius: radius.xs,
    backgroundColor: colors.accentBlueSoft,
    alignItems: 'center',
    justifyContent: 'center',
  },
  detailTextSlot: { flex: 1, minWidth: 0 },
  detailLabel: { ...typography.label, fontSize: 11, color: colors.inkFaint },
  detailValue: { ...typography.bodySm, fontSize: 14, color: colors.ink, marginTop: 1 },
  editFieldInlineWrap: { flex: 1 },
  /** Shadow never sits on the clipped card itself — see phase0-notes.md Recipe 1. */
  franchiseCardShadow: {
    shadowColor: colors.accentGreen,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.26,
    shadowRadius: 20,
    elevation: 6,
  },
  franchiseCard: {
    borderRadius: radius.md3,
    backgroundColor: colors.accentGreen,
    padding: spacing.md,
    overflow: 'hidden',
  },
  franchiseRow: { flexDirection: 'row', alignItems: 'center', gap: spacing.md },
  franchiseIconTile: {
    width: 44,
    height: 44,
    borderRadius: radius.md,
    backgroundColor: 'rgba(255,255,255,0.2)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.28)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  franchiseTextSlot: { flex: 1, minWidth: 0 },
  franchiseTitle: { ...typography.bodyStrong, color: colors.white },
  franchiseSubtitle: { ...typography.caption, fontSize: 12, color: colors.white, opacity: 0.82, marginTop: 1 },
  sectionLabel: { ...typography.label, color: colors.inkSoft },
  navGroup: {
    backgroundColor: colors.panel,
    borderRadius: radius.md3,
    paddingHorizontal: spacing.lg,
    ...panelShadow,
  },
  navIconTile: {
    width: 38,
    height: 38,
    borderRadius: radius.md,
    backgroundColor: colors.accentBlueSoft,
    alignItems: 'center',
    justifyContent: 'center',
  },
});
