import { StyleSheet } from 'react-native';
import { colors, fontFamily, radius, spacing, typography } from '@trisakay/ui';

export const styles = StyleSheet.create({
  scrim: { flex: 1, backgroundColor: colors.overlay, justifyContent: 'flex-end' },
  sheet: {
    backgroundColor: colors.white,
    borderTopLeftRadius: radius.sheetTop,
    borderTopRightRadius: radius.sheetTop,
    paddingTop: 10,
    paddingHorizontal: 18,
    gap: spacing.md,
  },
  handle: { width: 40, height: 4, borderRadius: 2, backgroundColor: colors.line, alignSelf: 'center', marginBottom: spacing.xs },
  title: { fontFamily: fontFamily.extrabold, fontSize: 21, lineHeight: 27, letterSpacing: -0.4, color: colors.ink },
  body: { ...typography.body, fontSize: 14, lineHeight: 21, color: colors.inkSoft },
  options: { gap: spacing.sm },
  option: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.md,
    minHeight: 52,
    borderRadius: radius.sm2,
    paddingHorizontal: 14,
    borderWidth: 1.5,
    borderColor: colors.line,
  },
  optionSelected: { borderColor: colors.accentBlue, backgroundColor: colors.accentBlueSoft },
  radio: { width: 20, height: 20, borderRadius: 10, borderWidth: 2, borderColor: colors.lineStrong },
  radioSelected: { borderWidth: 6, borderColor: colors.accentBlue, backgroundColor: colors.white },
  optionLabel: { ...typography.body, fontSize: 14.5, color: colors.ink, flex: 1 },
  optionLabelSelected: { fontFamily: fontFamily.semibold },
  buttons: { flexDirection: 'row', gap: spacing.sm, paddingTop: spacing.xs },
  keepButtonWrap: { flex: 1, minHeight: 54, borderRadius: radius.md3, overflow: 'hidden' },
  keepButton: { flex: 1, alignItems: 'center', justifyContent: 'center' },
  keepButtonText: { fontFamily: fontFamily.bold, fontSize: 15.5, color: colors.white },
  cancelButton: {
    flex: 1,
    minHeight: 54,
    borderRadius: radius.md3,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1.5,
    borderColor: colors.danger,
  },
  cancelButtonDisabled: { borderWidth: 0, backgroundColor: colors.fill },
  cancelButtonText: { fontFamily: fontFamily.bold, fontSize: 15.5, color: colors.danger },
  cancelButtonTextDisabled: { color: colors.inkFaint },
});
