import { StyleSheet } from 'react-native';
import { colors, radius, spacing, typography } from '@trisakay/ui';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: colors.bg },
  flex1: { flex: 1 },

  headerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.md,
    paddingHorizontal: spacing.lg,
    paddingTop: spacing.xs,
    paddingBottom: spacing.sm,
  },
  headerTile: {
    width: 40,
    height: 40,
    borderRadius: radius.sm2,
    backgroundColor: colors.panel,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: colors.accentBlue,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.09,
    shadowRadius: 8,
    elevation: 2,
  },
  headerTitle: { ...typography.h3, fontFamily: typography.bodyStrong.fontFamily, fontSize: 18, lineHeight: 24, color: colors.ink, flex: 1 },
  headerStep: { ...typography.bodySm, color: colors.inkSoft },

  progressRow: { flexDirection: 'row', gap: spacing.sm, paddingHorizontal: spacing.lg, paddingBottom: spacing.md },
  progressSegment: { flex: 1, height: 5, borderRadius: 3 },

  scrollContent: {
    paddingHorizontal: spacing.lg,
    paddingTop: spacing.xs,
    paddingBottom: 100,
    gap: spacing.xl,
  },
  stepGroups: { gap: spacing.xl },
  group: { gap: spacing.sm },
  question: { ...typography.h3, fontFamily: typography.bodyStrong.fontFamily, fontSize: 17, lineHeight: 23, color: colors.ink },

  tripCard: {
    backgroundColor: colors.panel,
    borderRadius: radius.card,
    padding: spacing.md,
    gap: spacing.md,
    borderWidth: 1.5,
    borderColor: colors.accentBlue,
    shadowColor: colors.accentBlue,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 14,
    elevation: 3,
  },
  tripCardEmpty: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderWidth: 1,
    borderColor: colors.line,
    shadowOpacity: 0,
    elevation: 0,
  },
  tripCardDimmed: { opacity: 0.5 },
  tripPlaceholder: { ...typography.body, color: colors.inkFaint },
  tripTopRow: { flexDirection: 'row', alignItems: 'center', gap: spacing.sm },
  tripNameSlot: { flex: 1, gap: 1 },
  tripName: { ...typography.bodySm, color: colors.ink, flex: 1 },
  tripMeta: { ...typography.caption, fontSize: 12, color: colors.inkSoft },
  changeLink: { ...typography.chip, color: colors.accentBlue },
  routeBlock: { paddingTop: spacing.md, borderTopWidth: 1, borderTopColor: colors.lineSoft, gap: spacing.sm },
  routeLine: { ...typography.caption, fontSize: 13, lineHeight: 18, color: colors.ink },
  tripFare: { ...typography.bodyLg, color: colors.ink, alignSelf: 'flex-end' },

  pickerCard: { borderWidth: 1, borderColor: colors.line, borderRadius: radius.card, overflow: 'hidden' },
  pickerScroll: { maxHeight: 280 },

  radioRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    backgroundColor: colors.panel,
    borderWidth: 1,
    borderColor: colors.line,
    borderRadius: radius.card,
    paddingVertical: spacing.md,
    paddingHorizontal: spacing.md + 2,
  },
  radioRowSelected: {},
  radioRing: {
    width: 18,
    height: 18,
    borderRadius: 9,
    borderWidth: 2,
    borderColor: colors.line,
    alignItems: 'center',
    justifyContent: 'center',
  },
  radioRingSelected: { borderColor: colors.accentBlue },
  radioDot: { width: 8, height: 8, borderRadius: 4, backgroundColor: colors.accentBlue },
  radioTextSlot: { flex: 1, gap: 1 },
  radioTitle: { ...typography.bodySm, color: colors.ink },
  radioSub: { ...typography.caption, color: colors.inkSoft },

  categoryGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.sm },
  categoryTile: {
    width: '47.5%',
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    backgroundColor: colors.panel,
    borderRadius: radius.card,
    padding: spacing.md,
    borderWidth: 1,
    borderColor: colors.line,
    position: 'relative',
  },
  categoryTileSelected: {
    borderWidth: 1.5,
    borderColor: colors.accentBlue,
    shadowColor: colors.accentBlue,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 14,
    elevation: 3,
  },
  categoryLabel: { ...typography.bodySm, fontSize: 13, color: colors.ink, flexShrink: 1 },
  categoryCheckBadge: {
    position: 'absolute',
    top: -6,
    right: -6,
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: colors.accentBlue,
    borderWidth: 2,
    borderColor: colors.bg,
    alignItems: 'center',
    justifyContent: 'center',
  },

  summaryChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    backgroundColor: colors.fill,
    borderRadius: radius.md3,
    paddingVertical: spacing.sm + 2,
    paddingHorizontal: spacing.md,
  },
  summaryText: { ...typography.bodySm, fontSize: 13, color: colors.ink, flex: 1 },

  chipRow: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.sm, marginTop: spacing.sm },
  suggestionChip: {
    borderRadius: radius.pill,
    paddingVertical: spacing.xs + 2,
    paddingHorizontal: spacing.md,
    backgroundColor: colors.panel,
    borderWidth: 1,
    borderColor: colors.line,
  },
  suggestionChipSelected: { backgroundColor: colors.accentBlue, borderColor: colors.accentBlue },
  suggestionChipText: { fontSize: 12, lineHeight: 16, fontFamily: typography.bodyStrong.fontFamily, color: colors.inkSoft },
  suggestionChipTextSelected: { color: colors.white },

  fieldLabel: { ...typography.label, color: colors.inkSoft },
  evidenceLabelRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  evidenceCounter: { backgroundColor: colors.fill, borderRadius: radius.pill, paddingHorizontal: spacing.sm, paddingVertical: 2 },
  evidenceCounterText: { fontSize: 11, lineHeight: 16, fontFamily: typography.caption.fontFamily, color: colors.inkSoft },
  evidenceRow: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.sm, marginTop: spacing.sm },
  evidenceThumbWrap: { width: 76, height: 76 },
  evidenceThumb: { width: 76, height: 76, borderRadius: radius.md3 },
  evidenceThumbPlaceholder: { backgroundColor: colors.fill, alignItems: 'center', justifyContent: 'center' },
  evidenceRemove: {
    position: 'absolute',
    top: -6,
    right: -6,
    backgroundColor: colors.ink,
    borderRadius: 999,
    width: 22,
    height: 22,
    alignItems: 'center',
    justifyContent: 'center',
  },
  addPhotoTile: {
    flex: 1,
    height: 76,
    borderRadius: radius.md3,
    borderWidth: 1,
    borderStyle: 'dashed',
    borderColor: '#9FB9D4',
    backgroundColor: colors.panel,
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    paddingHorizontal: spacing.md,
  },
  addPhotoTileCompact: { flex: 0, width: 76, justifyContent: 'center', paddingHorizontal: 0 },
  addPhotoText: { ...typography.caption, fontSize: 12, color: colors.inkSoft, flexShrink: 1 },
  addPhotoTextStrong: { fontFamily: typography.bodyStrong.fontFamily, color: colors.accentBlue },
  error: { ...typography.caption, color: colors.danger, marginTop: spacing.sm },

  sentScroll: { paddingHorizontal: spacing.lg, paddingTop: spacing.xxl, paddingBottom: 160, alignItems: 'center', gap: spacing.md },
  sentIconHalo: {
    width: 96,
    height: 96,
    borderRadius: 48,
    backgroundColor: 'rgba(233,247,227,0.5)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  sentIconCircle: {
    width: 76,
    height: 76,
    borderRadius: 38,
    backgroundColor: colors.accentGreenSoft,
    alignItems: 'center',
    justifyContent: 'center',
  },
  sentTitle: { fontSize: 26, lineHeight: 32, fontFamily: typography.h1b.fontFamily, letterSpacing: -0.6, color: colors.ink, marginTop: spacing.md },
  sentMessage: { ...typography.body, fontSize: 14, lineHeight: 21, color: colors.inkSoft, textAlign: 'center', maxWidth: 300 },
  sentWarning: { ...typography.caption, color: colors.danger, textAlign: 'center' },

  referenceCard: {
    width: '100%',
    marginTop: spacing.md,
    borderRadius: radius.lg,
    padding: spacing.lg,
    backgroundColor: colors.accentBlue,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  referenceEyebrow: { ...typography.eyebrow, fontSize: 11, color: colors.white, opacity: 0.6 },
  referenceValue: { fontSize: 30, lineHeight: 36, fontFamily: typography.display.fontFamily, letterSpacing: -0.8, color: colors.white },
  copyButton: { borderWidth: 1, borderColor: 'rgba(255,255,255,0.34)', borderRadius: radius.md, paddingVertical: spacing.sm, paddingHorizontal: spacing.md },
  copyButtonText: { ...typography.bodySm, fontSize: 13, color: colors.white },

  nextCard: { width: '100%', backgroundColor: colors.panel, borderRadius: radius.md3, padding: spacing.lg, gap: spacing.md },
  sectionLabel: { ...typography.eyebrow, color: colors.inkSoft },
  nextRow: { flexDirection: 'row', gap: spacing.md, alignItems: 'flex-start' },
  nextTile: { width: 26, height: 26, borderRadius: 8, alignItems: 'center', justifyContent: 'center' },
  nextTileNumber: { fontSize: 12, fontFamily: typography.h1b.fontFamily, color: colors.accentBlue },
  nextTextSlot: { flex: 1, gap: 1 },
  nextTitle: { ...typography.bodySm, color: colors.ink },
  nextBody: { ...typography.caption, fontSize: 12.5, lineHeight: 18, color: colors.inkSoft },

  sentBottom: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    paddingHorizontal: spacing.lg,
    paddingTop: spacing.md,
    gap: spacing.xs,
  },
  backTextButton: { minHeight: 48, alignItems: 'center', justifyContent: 'center' },
  backTextButtonLabel: { ...typography.bodySm, color: colors.accentBlue },
});
